name: actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: dependency (ubuntu)
        run: |
          sudo apt-get -q update
          sudo apt-get -qy install \
              curl build-essential make cmake libc6-dev \
              gcc g++ gfortran intel-mkl-full \
              python3 python3-pip python3-pytest \
              python3-numpy python3-scipy python3-pandas python3-matplotlib \
              jupyter
          sudo pip3 install pytest pybind11

      - name: test
        run: |
          make
          make test
          make clean
